name: Bookstore API Tests

on:
# Run workflow on every push/merge to main
  push:
    branches: [ main ]   
# Run workflow on PR creation/updates targeting main
  pull_request:
    branches: [ main ]  
# Allow manual trigger from GitHub Actions UI 
  workflow_dispatch:      
    inputs:
      tags:
        description: 'Test tags to run (e.g. positive, negative, edge)'
        required: false
        default: ''
      baseUrl:
        description: 'Base URL for API'
        required: false
        default: 'https://fakerestapi.azurewebsites.net'
  schedule:
    # Nightly job: Run all tests at 2 AM UTC every day
    - cron: '0 2 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest   #Use latest Ubuntu runner

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx (for building Docker images efficiently)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # # 3. Cache Maven dependencies to speed up builds
      # - name: Cache Maven packages
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.m2
      #     key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-maven-

      # 4. Build Docker image for the test framework
      - name: Build Docker image
        run: docker build -t bookstore-api-tests .

      # 5. Ensure previous run artifacts are removed (avoid mixing results)
      - name: Clean previous Allure outputs
        if: always()
        run: |
          rm -rf ./allure-results || true
          rm -rf ./allure-report || true

      # 6. Run tests inside container
      # If the tests are triggered manually via workflow_dispatch with tags provided it will run the tests that match those tags
      # otherwise it will run the full test suite
      - name: Run tests
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.tags }}" ]; then
            echo "Running tests with tags: ${{ github.event.inputs.tags }}"
            docker run --name bookstore-tests \
              -e TAGS=${{ github.event.inputs.tags }} \
              -e BASE_URL=${{ github.event.inputs.baseUrl }} \
              bookstore-api-tests
          else
            echo "Running full test suite"
            docker run --name bookstore-tests \
              -e BASE_URL=https://fakerestapi.azurewebsites.net \
              bookstore-api-tests
          fi

      # 7. Copy Allure test results from container to host
      - name: Copy Allure results
        if: always()
        run: docker cp bookstore-tests:/app/target/allure-results ./allure-results


      # 10. Clean up Docker container
      - name: Cleanup container
        if: always()
        run: docker rm -f bookstore-tests || true


      # 8. Generate Allure HTML report
      - name: Generate Allure HTML report
        if: always()
        run: |
          npm install -g allure-commandline --save-dev
          allure generate ./allure-results --clean -o ./allure-report

      # 8. Upload Allure HTML report as artifact (available in GitHub Actions UI)
      # - name: Upload Allure HTML report
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: allure-html-report
      #     path: ./allure-report

      # 9. Deploy Allure report to GitHub Pages
      - name: Deploy Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report


      # 11. Print Allure report link
      - name: Show Allure Report Link
        if: always()
        run: |
          echo "Here is your report: https://MajaTrajkovska.github.io/bookstore-api-tests/"
          echo "Here is your report: https://MajaTrajkovska.github.io/bookstore-api-tests/" >> $GITHUB_STEP_SUMMARY
